name: Build
on:
  workflow_dispatch:
  create:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v7.0.1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v7.0.0
        with:
          node-version: 24
          package-manager-cache: false
      - run: npm install
      - run: npm run build
      - name: Build/release Electron app
        run: >-
          npx --no electron-builder --
          --publish ${{ startsWith(github.ref, 'refs/tags/v') && 'always' || 'never' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
